runtime: nodejs18 

env_variables:
  REACT_APP_API_URL: "https://memoirederecettes.ew.r.appspot.com" 

handlers:
- url: /static
  static_dir: build/static

- url: /.*
  static_files: build/index.html
  upload: build/index.html
